sudo: required
dist: trusty
language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

script:
  - cargo test

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install cargo-tarpaulin
      cargo tarpaulin --no-count --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
